### ISSUE TITLE
chain methods

### ISSUE THREAD

**Issue by raybellwaves** [raybellwaves/nbdime-git-diff-action#1]
Users does

```
steps:
- name: nbdime-git-diff
  uses: raybellwaves/nbdime-git-diff@VERSION
```

Instead of:

```
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.13"
    - name: nbdime-git-diff
      uses: raybellwaves/nbdime-git-diff@0.0.4
```
